# Site settings
title: Eduardo Budant
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Eduardo Budant
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: eduardobudant@gmail.com
github_username:  ebudant

# Google-analytics
google-analytics:
  id: "UA-112921058-1"

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-cayman